import { fetchFile } from "@ffmpeg/util";

import { getFFmpeg } from "./ffmpeg";

import type { OverlayPosition } from "@/types/geotag";
import type { VideoItem } from "@/types/video";

/* ============================================================
   OVERLAY POSITION
============================================================ */

export function overlayXY(
  position: OverlayPosition,
  margin: number,
): {
  x: string;
  y: string;
} {
  const m = String(Math.max(0, margin));

  switch (position) {
    case "top-left":
      return {
        x: m,
        y: m,
      };

    case "top-right":
      return {
        x: `main_w-overlay_w-${m}`,
        y: m,
      };

    case "bottom-left":
      return {
        x: m,
        y: `main_h-overlay_h-${m}`,
      };

    case "bottom-right":
      return {
        x: `main_w-overlay_w-${m}`,
        y: `main_h-overlay_h-${m}`,
      };

    case "bottom-center":
    default:
      return {
        x: "(main_w-overlay_w)/2",
        y: `main_h-overlay_h-${m}`,
      };
  }
}

/* ============================================================
   VIDEO TIMING
============================================================ */

export function computeTiming(item: VideoItem) {
  const duration = Number.isFinite(item.duration)
    ? Math.max(0, item.duration)
    : 0;

  const trimStart = Number.isFinite(
    item.settings.trimStart,
  )
    ? item.settings.trimStart
    : 0;

  const trimEnd = Number.isFinite(
    item.settings.trimEnd,
  )
    ? item.settings.trimEnd
    : duration;

  const start = Math.max(
    0,
    Math.min(trimStart, Math.max(0, duration - 0.1)),
  );

  const end = Math.max(
    start + 0.1,
    Math.min(trimEnd, duration || trimEnd),
  );

  const finalDuration = Math.max(
    0.1,
    end - start,
  );

  const percent = Math.max(
    1,
    Math.min(
      100,
      Number.isFinite(item.settings.percent)
        ? item.settings.percent
        : 30,
    ),
  );

  const geotagDuration =
    (finalDuration * percent) / 100;

  const overlayStart =
    item.settings.timing === "beginning"
      ? 0
      : Math.max(
          0,
          finalDuration - geotagDuration,
        );

  const overlayEnd =
    overlayStart + geotagDuration;

  return {
    start,
    end,
    finalDuration,
    geotagDuration,
    overlayStart,
    overlayEnd,
  };
}

/* ============================================================
   PROCESS ARGUMENTS
============================================================ */

export interface ProcessArgs {
  item: VideoItem;

  /*
   * This is the user's uploaded geotag image.
   *
   * It is NOT generated by the application.
   */
  overlayPng: Blob;

  onProgress: (progress: number) => void;
}

/* ============================================================
   GET SAFE FILE EXTENSION
============================================================ */

function getVideoExtension(file: File): string {
  const nameExtension =
    file.name
      .split(".")
      .pop()
      ?.toLowerCase()
      .replace(/[^a-z0-9]/g, "");

  if (
    nameExtension === "mp4" ||
    nameExtension === "mov" ||
    nameExtension === "webm" ||
    nameExtension === "mkv" ||
    nameExtension === "m4v"
  ) {
    return nameExtension;
  }

  /*
   * We intentionally use mp4 as the fallback.
   */
  return "mp4";
}

/* ============================================================
   GET IMAGE EXTENSION
============================================================ */

function getImageExtension(blob: Blob): string {
  const type = blob.type.toLowerCase();

  if (type.includes("png")) {
    return "png";
  }

  if (
    type.includes("jpeg") ||
    type.includes("jpg")
  ) {
    return "jpg";
  }

  if (type.includes("webp")) {
    return "webp";
  }

  /*
   * The uploaded image is still written as PNG.
   * FFmpeg can detect the actual content in most cases.
   */
  return "png";
}

/* ============================================================
   PROCESS VIDEO
============================================================ */

export async function processVideo({
  item,
  overlayPng,
  onProgress,
}: ProcessArgs): Promise<Blob> {
  /*
   * Validate video.
   */

  if (!item.file) {
    throw new Error(
      "No video file was provided.",
    );
  }

  if (!overlayPng) {
    throw new Error(
      "No geotag image was provided.",
    );
  }

  if (!item.width || !item.height) {
    throw new Error(
      "Could not determine the video dimensions.",
    );
  }

  /*
   * Load FFmpeg.
   */

  let ffmpeg;

  try {
    ffmpeg = await getFFmpeg();
  } catch (error) {
    throw new Error(
      error instanceof Error
        ? error.message
        : "FFmpeg could not be loaded.",
    );
  }

  const {
    start,
    finalDuration,
    overlayStart,
    overlayEnd,
  } = computeTiming(item);

  /*
   * Unique filenames.
   */

  const extension =
    getVideoExtension(item.file);

  const imageExtension =
    getImageExtension(overlayPng);

  const inName =
    `video_${item.id}.${extension}`;

  const imageName =
    `geotag_${item.id}.${imageExtension}`;

  const outName =
    `result_${item.id}.mp4`;

  /*
   * Progress handler.
   */

  const progressHandler = ({
    progress,
  }: {
    progress: number;
  }) => {
    const safeProgress =
      Number.isFinite(progress)
        ? progress
        : 0;

    const percent = Math.round(
      Math.max(
        0,
        Math.min(
          1,
          safeProgress,
        ),
      ) * 100,
    );

    onProgress(percent);
  };

  ffmpeg.on(
    "progress",
    progressHandler,
  );

  try {
    console.log(
      "[VideoProcessor] Starting processing:",
      item.file.name,
    );

    console.log(
      "[VideoProcessor] Video type:",
      item.file.type,
    );

    console.log(
      "[VideoProcessor] Video size:",
      item.file.size,
    );

    console.log(
      "[VideoProcessor] Geotag type:",
      overlayPng.type,
    );

    console.log(
      "[VideoProcessor] Geotag size:",
      overlayPng.size,
    );

    /*
     * ========================================================
     * WRITE VIDEO
     * ========================================================
     */

    await ffmpeg.writeFile(
      inName,
      await fetchFile(item.file),
    );

    /*
     * ========================================================
     * WRITE GEOTAG IMAGE
     * ========================================================
     */

    await ffmpeg.writeFile(
      imageName,
      await fetchFile(overlayPng),
    );

    /*
     * ========================================================
     * OVERLAY SIZE
     * ========================================================
     *
     * Width is controlled by:
     *
     *   scale
     *
     * Height is controlled by:
     *
     *   heightScale
     *
     */

    const widthScale = Math.max(
      0.01,
      Math.min(
        1,
        Number.isFinite(
          item.settings.scale,
        )
          ? item.settings.scale
          : 0.9,
      ),
    );

    const heightScale = Math.max(
      0.01,
      Math.min(
        1,
        Number.isFinite(
          item.settings.heightScale,
        )
          ? item.settings.heightScale
          : 0.2,
      ),
    );

    /*
     * FFmpeg expressions.
     */

    const overlayWidth =
      `max(2,iw*${widthScale})`;

    const overlayHeight =
      `max(2,ih*${heightScale})`;

    /*
     * ========================================================
     * POSITION
     * ========================================================
     */

    const { x, y } = overlayXY(
      item.settings.position,
      0,
    );

    /*
     * ========================================================
     * OPACITY
     * ========================================================
     */

    const opacity = Math.max(
      0,
      Math.min(
        1,
        Number.isFinite(
          item.settings.opacity,
        )
          ? item.settings.opacity
          : 1,
      ),
    );

    /*
     * ========================================================
     * FILTER
     * ========================================================
     *
     * [1:v]
     *     geotag image
     *
     * scale
     *     resize image
     *
     * format=rgba
     *     ensure alpha channel
     *
     * colorchannelmixer
     *     opacity
     *
     * [ov]
     *     overlay stream
     *
     * [0:v][ov]
     *     video + geotag
     */

    const filter =
      `[1:v]` +
      `scale=${overlayWidth}:${overlayHeight}:force_original_aspect_ratio=decrease,` +
      `pad=ceil(iw/2)*2:ceil(ih/2)*2:(ow-iw)/2:(oh-ih)/2:color=black@0,` +
      `format=rgba,` +
      `colorchannelmixer=aa=${opacity}` +
      `[ov];` +

      `[0:v][ov]` +
      `overlay=${x}:${y}:` +
      `enable='between(t,${overlayStart.toFixed(
        3,
      )},${overlayEnd.toFixed(
        3,
      )})':` +
      `format=auto` +
      `[v]`;

    console.log(
      "[VideoProcessor] Filter:",
      filter,
    );

    /*
     * ========================================================
     * FFMPEG COMMAND
     * ========================================================
     */

    const args = [
      /*
       * Start point.
       */
      "-ss",
      start.toFixed(3),

      /*
       * Input video.
       */
      "-i",
      inName,

      /*
       * Loop the uploaded geotag image.
       */
      "-loop",
      "1",

      /*
       * Geotag input.
       */
      "-i",
      imageName,

      /*
       * Filter.
       */
      "-filter_complex",
      filter,

      /*
       * Video output.
       */
      "-map",
      "[v]",

      /*
       * Audio if available.
       */
      "-map",
      "0:a?",

      /*
       * Final duration.
       */
      "-t",
      finalDuration.toFixed(3),

      /*
       * Video encoder.
       */
      "-c:v",
      "libx264",

      /*
       * Encoding speed.
       */
      "-preset",
      "ultrafast",

      /*
       * Quality.
       */
      "-crf",
      "26",

      /*
       * Browser-compatible pixel format.
       */
      "-pix_fmt",
      "yuv420p",

      /*
       * Audio.
       */
      "-c:a",
      "aac",

      "-b:a",
      "128k",

      /*
       * Make MP4 seekable.
       */
      "-movflags",
      "+faststart",

      /*
       * Output.
       */
      outName,
    ];

    console.log(
      "[VideoProcessor] FFmpeg arguments:",
      args,
    );

    /*
     * ========================================================
     * EXECUTE
     * ========================================================
     */

    const exitCode =
      await ffmpeg.exec(args);

    console.log(
      "[VideoProcessor] FFmpeg exit code:",
      exitCode,
    );

    if (exitCode !== 0) {
      throw new Error(
        `FFmpeg exited with code ${exitCode}. Check the browser console for the FFmpeg log.`,
      );
    }

    /*
     * ========================================================
     * READ OUTPUT
     * ========================================================
     */

    const output =
      await ffmpeg.readFile(
        outName,
      );

    if (
      typeof output === "string"
    ) {
      throw new Error(
        "FFmpeg returned text instead of a video file.",
      );
    }

    const copy =
      new Uint8Array(output);

    if (copy.byteLength === 0) {
      throw new Error(
        "FFmpeg created an empty output file.",
      );
    }

    console.log(
      "[VideoProcessor] Output size:",
      copy.byteLength,
    );

    onProgress(100);

    return new Blob(
      [copy],
      {
        type: "video/mp4",
      },
    );
  } catch (error) {
    console.error(
      "========================================",
    );

    console.error(
      "[VideoProcessor] FAILED",
    );

    console.error(
      error,
    );

    console.error(
      "========================================",
    );

    /*
     * IMPORTANT:
     *
     * Do NOT hide the original error anymore.
     */

    if (error instanceof Error) {
      throw new Error(
        error.message,
      );
    }

    throw new Error(
      "Video processing failed. Check the browser console for the FFmpeg error.",
    );
  } finally {
    /*
     * Remove progress listener.
     */

    ffmpeg.off(
      "progress",
      progressHandler,
    );

    /*
     * Clean FFmpeg virtual filesystem.
     */

    for (const file of [
      inName,
      imageName,
      outName,
    ]) {
      try {
        await ffmpeg.deleteFile(
          file,
        );
      } catch {
        /*
         * Ignore cleanup errors.
         */
      }
    }
  }
}
