import { fetchFile } from "@ffmpeg/util";

import { getFFmpeg } from "./ffmpeg";

import type { OverlayPosition } from "@/types/geotag";
import type { VideoItem } from "@/types/video";

export function overlayXY(
  position: OverlayPosition,
  margin: number,
): {
  x: string;
  y: string;
} {
  const m = String(margin);

  switch (position) {
    case "top-left":
      return {
        x: m,
        y: m,
      };

    case "top-right":
      return {
        x: `main_w-overlay_w-${m}`,
        y: m,
      };

    case "bottom-left":
      return {
        x: m,
        y: `main_h-overlay_h-${m}`,
      };

    case "bottom-right":
      return {
        x: `main_w-overlay_w-${m}`,
        y: `main_h-overlay_h-${m}`,
      };

    case "bottom-center":
    default:
      return {
        x: "(main_w-overlay_w)/2",
        y: `main_h-overlay_h-${m}`,
      };
  }
}

export function computeTiming(item: VideoItem) {
  const start = Math.max(
    0,
    Math.min(
      item.settings.trimStart,
      item.duration,
    ),
  );

  const end = Math.max(
    start + 0.1,
    Math.min(
      item.settings.trimEnd,
      item.duration || item.settings.trimEnd,
    ),
  );

  const finalDuration = end - start;

  const geotagDuration =
    (finalDuration * item.settings.percent) / 100;

  const overlayStart =
    item.settings.timing === "beginning"
      ? 0
      : Math.max(
          0,
          finalDuration - geotagDuration,
        );

  const overlayEnd =
    overlayStart + geotagDuration;

  return {
    start,
    end,
    finalDuration,
    geotagDuration,
    overlayStart,
    overlayEnd,
  };
}

export interface ProcessArgs {
  item: VideoItem;

  /*
   * The user's uploaded geotag image.
   *
   * File extends Blob, so the image selected
   * from <input type="file"> can be passed here
   * without converting it first.
   */
  overlayPng: Blob;

  onProgress: (p: number) => void;
}

export async function processVideo({
  item,
  overlayPng,
  onProgress,
}: ProcessArgs): Promise<Blob> {
  const ffmpeg = await getFFmpeg();

  const {
    start,
    finalDuration,
    overlayStart,
    overlayEnd,
  } = computeTiming(item);

  /*
   * Give every FFmpeg file a unique name.
   */

  const extension =
    item.file.name
      .split(".")
      .pop()
      ?.toLowerCase() || "mp4";

  const inName = `in_${item.id}.${extension}`;

  /*
   * We keep the name .png because the processing
   * pipeline expects an image input.
   *
   * FFmpeg detects the actual image data.
   */
  const pngName = `ov_${item.id}.png`;

  const outFile = `out_${item.id}.mp4`;

  const handler = ({
    progress,
  }: {
    progress: number;
  }) => {
    const pct = Math.max(
      0,
      Math.min(
        100,
        Math.round(progress * 100),
      ),
    );

    onProgress(pct);
  };

  ffmpeg.on("progress", handler);

  try {
    /*
     * ============================================================
     * WRITE VIDEO
     * ============================================================
     */

    await ffmpeg.writeFile(
      inName,
      await fetchFile(item.file),
    );

    /*
     * ============================================================
     * WRITE USER'S GEOTAG IMAGE
     * ============================================================
     *
     * IMPORTANT:
     *
     * This is NOT generated by the application.
     *
     * It is the exact image uploaded by the user.
     */

    await ffmpeg.writeFile(
      pngName,
      await fetchFile(overlayPng),
    );

    /*
     * ============================================================
     * OVERLAY WIDTH
     * ============================================================
     *
     * scale:
     *
     * 1.0 = 100% of video width
     * 0.75 = 75%
     * 0.50 = 50%
     * etc.
     */

    const widthScale = Math.max(
      0.01,
      Math.min(
        1,
        item.settings.scale,
      ),
    );

    /*
     * ============================================================
     * OVERLAY HEIGHT
     * ============================================================
     *
     * We calculate height automatically using -1.
     *
     * This is important because your uploaded geotag image
     * should NOT become stretched or squashed.
     *
     * FFmpeg will preserve its original aspect ratio.
     */

    const overlayW =
      `main_w*${widthScale}`;

    const overlayH = "-1";

    /*
     * ============================================================
     * POSITION
     * ============================================================
     */

    const { x, y } = overlayXY(
      item.settings.position,
      0,
    );

    /*
     * ============================================================
     * OPACITY
     * ============================================================
     */

    const alpha = Math.max(
      0,
      Math.min(
        1,
        item.settings.opacity,
      ),
    );

    /*
     * ============================================================
     * FILTER
     * ============================================================
     *
     * [1:v]
     *
     * = uploaded geotag image
     *
     * [0:v]
     *
     * = original video
     *
     * The geotag image is resized while preserving
     * its original aspect ratio.
     */

    const filter =
      `[1:v]` +
      `scale=${overlayW}:${overlayH},` +
      `format=rgba,` +
      `colorchannelmixer=aa=${alpha}` +
      `[ov];` +

      `[0:v][ov]` +
      `overlay=${x}:${y}` +
      `:enable='between(t,${overlayStart.toFixed(
        3,
      )},${overlayEnd.toFixed(
        3,
      )})'` +
      `:format=auto` +
      `[v]`;

    /*
     * ============================================================
     * FFMPEG COMMAND
     * ============================================================
     */

    const args = [
      /*
       * Trim start
       */
      "-ss",
      start.toFixed(3),

      /*
       * Input video
       */
      "-i",
      inName,

      /*
       * Keep image running for entire video.
       */
      "-loop",
      "1",

      /*
       * Uploaded geotag image
       */
      "-i",
      pngName,

      /*
       * Overlay filter
       */
      "-filter_complex",
      filter,

      /*
       * Video output
       */
      "-map",
      "[v]",

      /*
       * Keep original audio if available.
       */
      "-map",
      "0:a?",

      /*
       * Final duration
       */
      "-t",
      finalDuration.toFixed(3),

      /*
       * Video codec
       */
      "-c:v",
      "libx264",

      /*
       * Faster browser processing.
       */
      "-preset",
      "ultrafast",

      /*
       * Video quality.
       */
      "-crf",
      "26",

      /*
       * Browser-compatible pixel format.
       */
      "-pix_fmt",
      "yuv420p",

      /*
       * Audio codec.
       */
      "-c:a",
      "aac",

      "-b:a",
      "128k",

      /*
       * Better MP4 playback.
       */
      "-movflags",
      "+faststart",

      /*
       * Output.
       */
      outFile,
    ];

    /*
     * ============================================================
     * RUN FFMPEG
     * ============================================================
     */

    const code = await ffmpeg.exec(args);

    if (code !== 0) {
      throw new Error(
        "encode-failed",
      );
    }

    /*
     * ============================================================
     * READ OUTPUT
     * ============================================================
     */

    const data = (await ffmpeg.readFile(
      outFile,
    )) as Uint8Array;

    /*
     * Make a copy because FFmpeg's underlying
     * memory may be reused after cleanup.
     */

    const copy = new Uint8Array(data);

    return new Blob(
      [copy],
      {
        type: "video/mp4",
      },
    );
  } catch (error) {
    console.error(
      "Video processing error:",
      error,
    );

    throw new Error(
      "Unable to process this video in your browser. Try using an MP4 video or a shorter/smaller video.",
    );
  } finally {
    /*
     * ============================================================
     * REMOVE PROGRESS LISTENER
     * ============================================================
     */

    ffmpeg.off(
      "progress",
      handler,
    );

    /*
     * ============================================================
     * CLEAN FFMPEG FILES
     * ============================================================
     */

    for (const file of [
      inName,
      pngName,
      outFile,
    ]) {
      try {
        await ffmpeg.deleteFile(
          file,
        );
      } catch {
        /*
         * Ignore cleanup errors.
         */
      }
    }
  }
}
